apiVersion: v1
metadata:
  name: {{ .Release.Name }}
stringData:
  secret.properties: |-
    db_host: {{ .Values.db.host | quote }}
    db_username: {{ .Values.db.username | quote }}
    db_password: {{ .Values.db.password | quote }}
type: Opaque
kind: Secret
