apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-demo
  template:
    metadata:
      labels:
        app: greeting-demo
    spec:
      containers:
      - name: greeting-demo
        image: quay.io/lordofthejars/greetings-jvm:1.0.0
        imagePullPolicy: Always
        volumeMounts:
        - name: greeting-sec
          mountPath: "/etc/sec" 
          readOnly: true
        ports:
        - containerPort: 8080
      volumes:
      - name: greeting-sec
        secret:
          secretName: greeting-secret
