apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: hello
    image: alpine
    command: ["cat", "/secrets/secret.properties"]
    volumeMounts:
    - name: secret
      mountPath: "/secrets"
      readOnly: true
  restartPolicy: Never
  volumes:
  - name: secret
    secret:
      secretName: hello

