apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: welcome-cluster-ops
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: http://gitea:3000/gitea/kubernetes-secrets-source.git
    targetRevision: HEAD
    path: welcome-message-gitops/cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: default