---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/lordofthejars/kubernetes-secrets-source.git
    app.quarkus.io/build-timestamp: 2021-03-09 - 15:59:07 +0000
    app.quarkus.io/commit-id: 1fba460a4cce99fe47954107c720290179673c74
  labels:
    app.kubernetes.io/name: name-generator
    app.kubernetes.io/version: 1.0.0
  name: name-generator
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: name-generator
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/lordofthejars/kubernetes-secrets-source.git
    app.quarkus.io/build-timestamp: 2021-03-09 - 15:59:07 +0000
    app.quarkus.io/commit-id: 1fba460a4cce99fe47954107c720290179673c74
  labels:
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: name-generator
  name: name-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/name: name-generator
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://github.com/lordofthejars/kubernetes-secrets-source.git
        app.quarkus.io/build-timestamp: 2021-03-09 - 15:59:07 +0000
        app.quarkus.io/commit-id: 1fba460a4cce99fe47954107c720290179673c74
      labels:
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/name: name-generator
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/lordofthejars/name-generator:1.0.0
        imagePullPolicy: Always
        name: name-generator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
